config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'terms', to: 'terms#index'
  get 'about', to: 'about#index'
  get 'faq', to: 'faq#index'
  resources :tasks
  resources :users
  resources :projects

end

app/models/common_question.rb
class CommonQuestion
  def self.question
    #frequestion = [{question: ["What is gCamp?", "How do I join gCamp?", "When will gCamp be done?"] },{answer: ["gCamp is an awesome tool that is going to change your life. gCamp is your one stop shop to organize all your tasks. You'll also be able to track comments that you and others make. gCamp may eventually replace all need for paper and pens in the entire world. Well, maybe not, but it's going to be pretty cool.","As soon as it's ready for the public, you'll see a signup link in the upper right. Once that's there, just click it and fill in the form!","When will gCamp be finished?","gCamp is a work in progress. That being said, it should be fully functional in the next few weeks. Functional. Check in daily for new features and awesome functionality. It's going to blow your mind. Organization is just a click away. Amazing!"]}]
    [{question: "What is gCamp?", answer: "gCamp is an awesome tool that is going to change your life. gCamp is your one stop shop to organize all your tasks. You'll also be able to track comments that you and others make. gCamp may eventually replace all need for paper and pens in the entire world. Well, maybe not, but it's going to be pretty cool."}, {question: "How do I join gCamp?", answer: "As soon as it's ready for the public, you'll see a signup link in the upper right. Once that's there, just click it and fill in the form!"}, {question: "When will gCamp be finished?", answer: "gCamp is a work in progress. That being said, it should be fully functional in the next few weeks. Functional. Check in daily for new features and awesome functionality. It's going to blow your mind. Organization is just a click away. Amazing!"}]
  end

  def self.links
    links=[]
    question.each do |k|
      links<< k[:question]
    end
    links

  end



end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all
end

app/controllers/application_helper.rb
module ApplicationHelper
  def comment
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
    @quote= CommonQuestion.question
    @link= CommonQuestion.links

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :show, :update]

  def index
    @projects=Project.all
  end

  def new
    @project= Project.new
  end

  def create
    @project=Project.new(project_params)
    if @project.save
      flash[:success] = "Project was successfully created"
      redirect_to projects_pathc
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @project.update(project_params)
      flash[:success] = "Project was successfully updated"
      redirect_to @project
    else
      render :edit

    end
  end

  def destroy
    flash[:success] = "Project was successfully deleted"
    project=Project.find(params[:id])
    project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project=Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks= Task.all
  end

  def new
    @task= Task.new
  end


  def create
   @task = Task.new(task_params)
   if @task.save
     flash[:notice]= 'Task has been created'
     redirect_to task_path(@task)
   else
     render :new
   end
  end

  def edit
  end

  def show
  end

  def update
    if @task.update(task_params)
      @task.completed=false
      flash[:notice]='Task was successfully updated.'
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy

    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :completed, :due_date)
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users=User.all
  end

  def new
    @user= User.new
  end

  def create
    flash[:notice]="User was successfully created"
    @user=User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      flash[:notice]="User was successfully updated"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    flash[:notice]="User was successfully deleted"
    @user.destroy
    redirect_to users_path

  end

  private

  def set_user
    @user=User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @quotes_array=[{"quote"=>"gCamp has changed my life! It\'s the best tool I\'ve ever used.", "contributor"=>"Cayla Hayes"}, {"quote"=>'"Before gCamp I was a disorderly slob. Now I\'m more organized than I\'ve ever been"', "contributor"=>"Leta Jaskolski"}, {"quote"=>'"Don\'t hesitate - sign up right now! You\'ll never be the same."', "contributor"=>"Lavern Upton"}]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
  <div class="page-header">
    <h1>About</h1>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= image_tag("relaxin.jpg", class:"img-responsive") %>
      <p class="lead"></p>
    </div>
    <div class="col-md-8">
      <p> We are dedicated to the makers, the creators, the risk-takers</p>
      <p> We wake up in the middle of the night and furiously write down ideas about how to make our online life better.</p>
      <p> Human collaboration and communication is what drives us, and it infuses every feature of Gcamp.</p>
    </div>

  </div>

app/views/faq/index.html.erb
  <div class="page-header">
    <h1>Frequently Asked Questions</h1>
  </div>
    <div class= "un_link">
    <ul>
      <li><%=link_to(@link[0], "#"+@link[0].parameterize)%></li>
      <li><%=link_to(@link[1], "#"+@link[1].parameterize)%></li>
      <li><%=link_to(@link[2], "#"+@link[2].parameterize)%></li>
    </ul>
    </div>



  <div class="col-md-6">
    <% @quote.each do |k|%>

        <%= content_tag :a, '', name: k[:question].parameterize%>
        <h3><%=  k[:question] %></h3>
        <p><%=  k[:answer]%></p>
        <%=link_to("Top", "#top")%>

    <%end%>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">


  <div class="container">
      <%=link_to("gCamp", root_path, class:"navbar-brand") %>
  </div>

  </nav>


<div class="container">
  <% if flash[:notice]%>
    <div class = "alert alert-success text-center">
      <%= flash[:notice] %>
    </div>
  <%end%>
<%= yield %>

  <footer>

        <%= link_to("Terms",terms_path) %> | <%= link_to("About",about_path) %> | <%= link_to("FAQ", faq_path) %> | <%= link_to "Tasks", tasks_path%>
         | <%= link_to "Users", users_path%> | <%= link_to "Projects", projects_path %>
        <%=link_to(image_tag("galvanize.png", class:"link_image"), "https://students.gschool.it/students/282")%>
        <%=link_to(image_tag("Twitter.png", class:"link_image"), "https://twitter.com/brennanator90")%>
        <%=link_to(image_tag("Github.png", class:"link_image"), "https://github.com/ipbrennan90")%>
        <%=link_to(image_tag("linked_in.jpg", class:"link_image"), "https://www.linkedin.com/pub/ian-brennan/46/256/81b")%>
  </footer>


</div>


</body>

</html>

app/views/projects/_form.html.erb
<%= form_for @project, html: {class: "form-horizontal"} do |f|  %>


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label :name %>
      </div>
      <div class="col-sm-4">
          <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10 ">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Back", projects_path, class: "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/projects/edit.html.erb
<h1 class= "page-header">Edit Project</h1>
<% comment do %>
<ul class = "breadcrumb">
  <li> <%= link_to "Projects", projects_path %> > <%= link_to @project.name, project_path(@project)  %> > Editing Project</li>
</ul>
<%end%>


<%= render "form" %>

app/views/projects/index.html.erb
<% if flash[:success]  %>
  <div class = "alert alert-success ">
    <%= flash[:success] %>
  </div>
<% end %>
<h1 class = "page-header">
  Projects
  <div class="pull-right">
    <%= link_to "New Project", new_project_path, class: "btn btn-info" %>
  </div>
</h1>




<table class = "table">
  <thead>
    <th>Name</th>
  </thead>
  <% @projects.each do |r| %>
  <tr>
    <td> <%= link_to r.name, project_path(r) %> </td>
  </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1 class = "page-header">New Project</h1>
<% comment do %>
<ul class = "breadcrumb">
  <li> <%= link_to "Projects", projects_path %> > New Task</li>
</ul>
<% end %>

<%= render "form" %>

app/views/projects/show.html.erb
  <% if flash[:success]  %>
    <div class = "alert alert-success ">
      <%= flash[:success] %>
    </div>
  <% end %>

  <h1 class = "page-header">
    <%= @project.name %>
    <div class = "pull-right">
      <%= link_to "Edit", edit_project_path(@project), class: "btn btn-info" %>
      <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </h1>
  <% comment do %>
  <ul class = "breadcrumb">
    <li> <%= link_to "Projects", projects_path %> > <%= @project.name  %></li>
  </ul>
  <% end %>

app/views/tasks/_form.html.erb
<%= form_for @task, html: {class: "form-horizontal"} do |f|  %>


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label :description %>
      </div>
      <div class="col-sm-4">
          <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label :due_date %>
      </div>
      <div class="col-sm-2">
          <%= f.date_field :due_date, class: "form-control" %>
      </div>
    </div>



    <% unless @task.new_record?  %>

    <div class = "form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.check_box :completed %>
        <%= f.label :completed %>
      </div>
    </div>

    <% end %>



    <div class = "form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'Cancel', tasks_path, class: "btn btn-default" %>
      </div>
    </div>





<% end %>

app/views/tasks/edit.html.erb
  <h1>Edit Task</h1>
  <ol class = "breadcrumb">
    <li> <%= link_to "Tasks", tasks_path %> > <%= link_to @task.description , task_path(@task) %> > Editing Task </li>
  </ol>

  <%= render "form" %>

app/views/tasks/index.html.erb
  <h1 class="page-header"> Tasks
     <div class= "pull-right">

         <%= link_to 'New Task', new_task_path, class: "btn btn-info" %>

      </div>
  </h1>

  <table class= "table">


    <thead>
      <tr>
        <th>Description</th>
        <th align= "left">Due Date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |t| %>
      <tr>
        <td>
          <% if t.completed %>
            <s><%=link_to t.description, task_path(t) %></s>
          <% else %>
            <%=link_to t.description, task_path(t) %>
          <% end %>
        </td>
        <td>
          <% if t.due_date %>
            <%= t.due_date.strftime("%m/%d/%Y") %>
          <% end %>
        </td>
        <td>
          <div class = "pull-right">
            <%= link_to 'Edit', edit_task_path(t), class: "btn btn-info" %>
            <%= link_to 'Delete', task_path(t), method: :delete,class: "btn btn-danger"%>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/tasks/new.html.erb
<h1> New Task </h1>
<ol class = "breadcrumb">
  <li> <%= link_to "Tasks", tasks_path %> > New Task </li>
</ol>

<%= render "form" %>

app/views/tasks/show.html.erb
  <h1 class="page-header">
    <%if @task.completed==true then %>
      <s><%= @task.description %></s>
    <% else %>
      <%= @task.description %>
    <% end %>

    <div class= "pull-right">
         <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-info" %>
    </div>
  </h1>

  <ol class = "breadcrumb">
    <li> <%= link_to "Tasks", tasks_path %> > <%= @task.description %></li>
  </ol>

  <p>
    <strong>
      Due On:
    </strong>
      <% if @task.due_date %>
        <%= @task.due_date.strftime("%m/%d/%Y") %>
      <% end %>
  jj</p>

app/views/terms/index.html.erb
  <div class="page-header">
    <h1>Terms</h1>
  </div>

  <p> gCamp is not responsible for anything, unless it is positive. </p>
  <p> You may not take us to court. For anything. Ever. </p>

app/views/users/_form.html.erb
  <%= form_for @user, html: {class: "form-horizontal"} do |u| %>

  <div class = "form-group">
    <div class = "col-sm-2">
      <%= u.label :first_name, class: "control-label" %>
    </div>
    <div class = "col-sm-4">
      <%= u.text_field :first_name, class: "form-control " %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "col-sm-2">
      <%= u.label :last_name, class: "control-label" %>
    </div>
    <div class = "col-sm-4">
      <%= u.text_field :last_name, class: "form-control " %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "col-sm-2">
      <%= u.label :email, class: "control-label" %>
    </div>
    <div class = "col-sm-4">
      <%= u.email_field :email, class: "form-control " %>
    </div>
  </div>


  <div class = "form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= u.submit class: "btn btn-primary" %>
      <%= link_to 'Cancel', users_path, class: "btn btn-default" %>

    </div>
  </div>






  <% end %>
  <%if params[:action] == "edit" %>
  <div class = "row">
      <div class = "col-sm-offset-2 col-sm-4">
        <div class = "well text-center">


            <%= link_to "Delete User", user_path(@user), method: :delete,data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>

        </div>
      </div>
  </div>
  <% end %>

app/views/users/edit.html.erb
<h1 class = "page-header"> Edit User </h1>
<%= render "form" %>

app/views/users/index.html.erb
  <h1 class = "page-header">
      Users
      <div class = "pull-right">
        <%= link_to "New User", new_user_path, class: "btn btn-info" %>
      </div>
  </h1>




    <table class = "table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |u| %>

        <tr>
          <td>
            <%=link_to u.first_name+" "+u.last_name, user_path(u) %>
          </td>
          <td>
            <%= mail_to u.email %>
          </td>

          <td>
            <div class = "pull-right">
              <%= link_to 'Edit', edit_user_path(u) %>
            </div>
          </td>

      </tr>


      <% end %>
  </table>

app/views/users/new.html.erb
<h1 class = "page-header"> New User </h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class = "page-header"> <%= @user.first_name+" "+@user.last_name %>
  <div class = "pull-right">
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-info" %>
  </div>
</h1>

<dl class="dl-horizontal">
  <dt>First Name</dt>
  <dd> <%= @user.first_name %> </dd>
  <dt>Last Name</dt>
  <dd> <%= @user.last_name %> </dd>
  <dt>Email</dt>
  <dd> <%= @user.email %> </dd>

</dl>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h1>gCamp</h1>
    <br></br>
    <p>Your life, organized</p>

  </div>

  <div class="row">
    <div class="bs-example" data-example-id="responsive-embed-16by9-iframe-youtube">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/IAkBYSbMYA8" allowfullscreen></iframe>
      </div>
    </div>